version: 0.2

phases:
  build:
    commands:
      - quasar build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: dist/pwa/book-butterfly
  name: book-butterfly-staging
